<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DoctorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('doctors')->insert([
            [
                'name' => 'Dr. Sarah Ahmed',
                'image' => 'uploads/team-1.jpg',
                'designation' => 'Orthodontist',
                'about' => 'Specializes in straightening teeth and correcting bites.',
                'additional_info' => 'Experienced with braces and Invisalign.',
                'address' => '123 Sunset Blvd, Los Angeles, CA, USA',
                'email' => 'sarah.ahmed@caldental.com',
                'phone' => '+1 (213) 555-1001',
                'twitter' => null,
                'facebook' => 'https://facebook.com/drsarahahmed',
                'instagram' => 'https://instagram.com/drsarahahmed',
                'linkedin' => null,
                'other_website' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Rajiv Kumar',
                'image' => 'uploads/team-2.jpg',
                'designation' => 'Periodontist',
                'about' => 'Expert in gum health and dental implants.',
                'additional_info' => 'Focuses on prevention and treatment of gum disease.',
                'address' => '456 Market St, San Francisco, CA, USA',
                'email' => 'rajiv.kumar@caldental.com',
                'phone' => '+1 (415) 555-2002',
                'twitter' => null,
                'facebook' => 'https://facebook.com/drrajivkumar',
                'instagram' => null,
                'linkedin' => null,
                'other_website' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Emily Carter',
                'image' => 'uploads/team-3.jpg',
                'designation' => 'Endodontist',
                'about' => 'Specializes in root canal treatments.',
                'additional_info' => 'Over 12 years of experience in painless dental care.',
                'address' => '789 Broadway, Sacramento, CA, USA',
                'email' => 'emily.carter@caldental.com',
                'phone' => '+1 (916) 555-3003',
                'twitter' => 'https://twitter.com/dremilycarter',
                'facebook' => null,
                'instagram' => null,
                'linkedin' => 'https://linkedin.com/in/dremilycarter',
                'other_website' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Hassan Ali',
                'image' => 'uploads/team-4.jpg',
                'designation' => 'Prosthodontist',
                'about' => 'Expert in dental crowns, bridges, and dentures.',
                'additional_info' => 'Helps restore smiles with precision.',
                'address' => '101 Main St, Fresno, CA, USA',
                'email' => 'hassan.ali@caldental.com',
                'phone' => '+1 (559) 555-4004',
                'twitter' => null,
                'facebook' => null,
                'instagram' => 'https://instagram.com/drhassanalidentist',
                'linkedin' => null,
                'other_website' => null,
                'status' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Laura White',
                'image' => 'uploads/team-5.jpg',
                'designation' => 'Oral Surgeon',
                'about' => 'Specializes in wisdom tooth extraction and oral surgeries.',
                'additional_info' => 'Certified in advanced surgical procedures.',
                'address' => '202 Palm Ave, San Diego, CA, USA',
                'email' => 'laura.white@caldental.com',
                'phone' => '+1 (619) 555-5005',
                'twitter' => null,
                'facebook' => 'https://facebook.com/drlaurawhite',
                'instagram' => null,
                'linkedin' => 'https://linkedin.com/in/drlaurawhite',
                'other_website' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Miguel Torres',
                'image' => 'uploads/team-6.jpg',
                'designation' => 'Pediatric Dentist',
                'about' => 'Dedicated to children’s oral health.',
                'additional_info' => 'Creates a fun and safe environment for kids.',
                'address' => '303 Maple St, San Jose, CA, USA',
                'email' => 'miguel.torres@caldental.com',
                'phone' => '+1 (408) 555-6006',
                'twitter' => 'https://twitter.com/drmiguelto',
                'facebook' => null,
                'instagram' => null,
                'linkedin' => null,
                'other_website' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Anita Sharma',
                'image' => 'uploads/team-7.jpg',
                'designation' => 'Oral Pathologist',
                'about' => 'Expert in diagnosing oral diseases.',
                'additional_info' => 'Researcher in oral cancer and infections.',
                'address' => '404 Elm St, Oakland, CA, USA',
                'email' => 'anita.sharma@caldental.com',
                'phone' => '+1 (510) 555-7007',
                'twitter' => null,
                'facebook' => 'https://facebook.com/dranitasharma',
                'instagram' => null,
                'linkedin' => 'https://linkedin.com/in/dranitasharma',
                'other_website' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Kevin Brown',
                'image' => 'uploads/team-8.jpg',
                'designation' => 'General Dentist',
                'about' => 'Provides comprehensive dental care and routine checkups.',
                'additional_info' => 'Over 20 years of experience in family dentistry.',
                'address' => '505 Beach Dr, Santa Monica, CA, USA',
                'email' => 'kevin.brown@caldental.com',
                'phone' => '+1 (310) 555-8008',
                'twitter' => null,
                'facebook' => null,
                'instagram' => 'https://instagram.com/drkevinbrown',
                'linkedin' => null,
                'other_website' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

    }
}
